phases:
  build:
    commands:
      - echo Build started on 'date'
      - mvn install
  post_build:
    commands:
      - echo Build completed on 'date'
      - mvn package
artifacts:
  files:
    - 'target/JenkinsWar.war'
